2025-03-03 18:48:22,707 - INFO - 正在验证: http://39.165.257hfhh52:9003/hls/1/index.m3u8
2025-03-03 18:48:22,707 - INFO - 正在验证: http://39.165hfdkbhb.218.252/hls/1/index.m3u8
2025-03-03 18:48:22,708 - INFO - 正在验证: http://39.165fgggg.218.252:9003/hls/1/index.m3u8
2025-03-03 18:48:22,709 - INFO - 正在验证: http://invalid.url:abc/hls/1/index.m3u8
2025-03-03 18:48:22,709 - INFO - 正在验证: https://example.com:8080/hls/1/index.m3u8
2025-03-03 18:48:52,749 - INFO - 已保存 0 个有效地址
2025-03-03 18:50:41,859 - IPTV-Scanner - DEBUG - 正在测试: http://39.165.257hfhh52:9003/hls/1/index.m3u8
2025-03-03 18:50:41,860 - IPTV-Scanner - DEBUG - 正在测试: http://39.165hfdkbhb.218.252/hls/1/index.m3u8
2025-03-03 18:50:41,860 - IPTV-Scanner - DEBUG - 正在测试: http://39.165fgggg.218.252:9003/hls/1/index.m3u8
2025-03-03 18:50:41,861 - IPTV-Scanner - DEBUG - 正在测试: http://192.168.1.1:8080/hls/1/index.m3u8
2025-03-03 18:50:41,861 - IPTV-Scanner - WARNING - URL标准化失败 [http://invalid.url:abc]: ValueError
2025-03-03 18:50:41,872 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d7880>: Failed to resolve '39.165.257hfhh52' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:41,942 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d74c0>: Failed to resolve '39.165hfdkbhb.218.252' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:41,973 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d7160>: Failed to resolve '39.165fgggg.218.252' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:41,979 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d6c20>: Failed to resolve '39.165.257hfhh52' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:41,986 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d42b0>: Failed to resolve '39.165.257hfhh52' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:42,000 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d4490>: Failed to resolve '39.165fgggg.218.252' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:42,008 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73d6a10>: Failed to resolve '39.165hfdkbhb.218.252' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:42,015 - IPTV-Scanner - DEBUG - 测速失败 [39.165.257hfhh52:9003/hls/23/ind]: ConnectionError
2025-03-03 18:50:42,026 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73c5870>: Failed to resolve '39.165fgggg.218.252' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:42,034 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fcbd73c5a50>: Failed to resolve '39.165hfdkbhb.218.252' ([Errno -2] Name or service not known)")': /hls/1/index.m3u8
2025-03-03 18:50:42,056 - IPTV-Scanner - DEBUG - 测速失败 [http://39.165hfdkbhb.218.252]: ConnectionError
2025-03-03 18:50:42,083 - IPTV-Scanner - DEBUG - 测速失败 [http://39.165fgggg.218.252:9003]: ConnectionError
2025-03-03 18:50:56,882 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcbd73d6e60>, 'Connection to 192.168.1.1 timed out. (connect timeout=15)')': /hls/1/index.m3u8
2025-03-03 18:51:11,897 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcbd73c5fc0>, 'Connection to 192.168.1.1 timed out. (connect timeout=15)')': /hls/1/index.m3u8
2025-03-03 18:51:26,913 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fcbd73c7f70>, 'Connection to 192.168.1.1 timed out. (connect timeout=15)')': /hls/1/index.m3u8
2025-03-03 18:51:41,930 - IPTV-Scanner - DEBUG - 测速失败 [192.168.1.1:8080/any/path]: ConnectTimeout
